### ISSUE TITLE
Поймай шарик

### ISSUE THREAD

**Issue by Ainoss** [pioterM/infa_2019_mekhraliev#1]
Реализация не полная, сделаны только 1 и 2 пункты задания. Основные недочеты:

- ООП не применяется, хотя первые попытки есть. В частности, после создания объекта ball1 он никак не используется. Можно обсудить на занятии подробнее.
- Обилие магических констант
- Остался мертвый код для перемещения шарика
- Форматирование не соответствует рекомендуемому (google PEP8)

Такое решение не получится оценить позитивно, поэтому целесообразно его доработать в ближайшее время. Можете обращаться напрямую, если есть конкретные вопросы.

**Comment by pioterM** [comment]
Вот окончательная версия лабораторной работы "Поймай шарик"
https://github.com/pioterM/infa_2019_mekhraliev/blob/master/ball/ball5.3.py

**Comment by Ainoss** [comment]
Реализация стала на порядок лучше!
Видно использование хорошей идеи родительского класса для унификации, но этот подход можно было развить (больше функций сделать общими методами). Это позволило бы сократить количество кода, например можно было бы использовать один общий массив элементов targets ([Пример](https://github.com/DeminAlex19/infa_2019_demin/blob/master/saveball.py#L114))
Принято!
